# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Main Entry Function To Check Data Consistency and Coding For Birth Evaluation
#'
#' @description
#' This is the main entry function to check consistency and coding birth data.
#'
#' @param paramFileName input paramter file name
#'
#' @export CalvingPrep_main
CalvingPrep_main <- function(paramFileName) {
    .Call(`_CalvingPrep_CalvingPrep_main`, paramFileName)
}

rcpp_hello <- function() {
    .Call(`_CalvingPrep_rcpp_hello`)
}

